name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the action to run every day at midnight (UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace 'x' with the desired Python version (e.g., '3.6', '3.7', '3.8', etc.)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python scholar-count.py